# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{cms_gallery}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Stephen McLeod"]
  s.date = %q{2011-01-28}
  s.description = %q{TODO: longer description of your gem}
  s.email = %q{stephen@theworkinggroup.ca}
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "app/controllers/admin/galleries_controller.rb",
    "app/controllers/admin/photos_controller.rb",
    "app/controllers/application_controller.rb",
    "app/models/gallery.rb",
    "app/models/photo.rb",
    "app/views/admin/_html_head.html.haml",
    "app/views/admin/_navigation.html.haml",
    "app/views/admin/galleries/_form.html.haml",
    "app/views/admin/galleries/edit.html.haml",
    "app/views/admin/galleries/index.html.haml",
    "app/views/admin/galleries/new.html.haml",
    "app/views/admin/photos/_file.html.haml",
    "app/views/admin/photos/_form.html.haml",
    "app/views/admin/photos/destroy.js.erb",
    "app/views/admin/photos/edit.html.haml",
    "app/views/admin/photos/index.html.haml",
    "app/views/admin/photos/new.html.haml",
    "app/views/content/_gallery.html.haml",
    "app/views/stylesheets/admin.sass",
    "app/views/stylesheets/gallery.sass",
    "cms_gallery.gemspec",
    "config/application.rb",
    "config/boot.rb",
    "config/database-example.yml",
    "config/database.yml",
    "config/environment.rb",
    "config/environments/development.rb",
    "config/environments/production.rb",
    "config/environments/production/database.yml",
    "config/environments/production/httpd.conf",
    "config/environments/test.rb",
    "config/routes.rb",
    "db/migrate/20101202211420_create_galleries.rb",
    "db/migrate/20101202211429_create_photos.rb",
    "lib/cms_gallery.rb",
    "lib/cms_gallery/engine.rb",
    "log/test.log",
    "public/images/prettyPhoto/dark_rounded/btnNext.png",
    "public/images/prettyPhoto/dark_rounded/btnPrevious.png",
    "public/images/prettyPhoto/dark_rounded/contentPattern.png",
    "public/images/prettyPhoto/dark_rounded/loader.gif",
    "public/images/prettyPhoto/dark_rounded/sprite.png",
    "public/images/prettyPhoto/dark_square/btnNext.png",
    "public/images/prettyPhoto/dark_square/btnPrevious.png",
    "public/images/prettyPhoto/dark_square/contentPattern.png",
    "public/images/prettyPhoto/dark_square/loader.gif",
    "public/images/prettyPhoto/dark_square/sprite.png",
    "public/images/prettyPhoto/facebook/btnNext.png",
    "public/images/prettyPhoto/facebook/btnPrevious.png",
    "public/images/prettyPhoto/facebook/loader.gif",
    "public/images/prettyPhoto/facebook/sprite.png",
    "public/images/prettyPhoto/facebook/untitled folder/contentPatternBottom.png",
    "public/images/prettyPhoto/facebook/untitled folder/contentPatternLeft.png",
    "public/images/prettyPhoto/facebook/untitled folder/contentPatternRight.png",
    "public/images/prettyPhoto/facebook/untitled folder/contentPatternTop.png",
    "public/images/prettyPhoto/facebook/untitled folder/sprite copy.png",
    "public/images/prettyPhoto/light_rounded/btnNext.png",
    "public/images/prettyPhoto/light_rounded/btnPrevious.png",
    "public/images/prettyPhoto/light_rounded/loader.gif",
    "public/images/prettyPhoto/light_rounded/sprite.png",
    "public/images/prettyPhoto/light_square/btnNext--.png",
    "public/images/prettyPhoto/light_square/btnNext.png",
    "public/images/prettyPhoto/light_square/btnPrevious--.png",
    "public/images/prettyPhoto/light_square/btnPrevious.png",
    "public/images/prettyPhoto/light_square/loader.gif",
    "public/images/prettyPhoto/light_square/sprite--.png",
    "public/images/prettyPhoto/light_square/sprite.png",
    "public/javascripts/admin.js",
    "public/javascripts/application.js",
    "public/javascripts/jquery.js",
    "public/javascripts/jquery.pretty_photo.js",
    "public/robots.txt",
    "public/stylesheets/.gitkeep",
    "public/stylesheets/admin.css",
    "public/stylesheets/common.css",
    "public/stylesheets/pretty_photo.css",
    "script/rails",
    "test/fixtures/galleries.yml",
    "test/fixtures/images/invalid_image.gif",
    "test/fixtures/images/test_image.jpg",
    "test/fixtures/photos.yml",
    "test/functional/admin/galleries_controller_test.rb",
    "test/functional/admin/photos_controller_test.rb",
    "test/helper.rb",
    "test/test_helper.rb",
    "test/unit/gallery_test.rb",
    "test/unit/photo_test.rb"
  ]
  s.homepage = %q{http://github.com/stephenmmcleod/cms_gallery}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{CMS Gallery is an easy to use, super simple gallery plugin for Comfortable Mexican Sofa.}
  s.test_files = [
    "test/functional/admin/galleries_controller_test.rb",
    "test/functional/admin/photos_controller_test.rb",
    "test/helper.rb",
    "test/test_helper.rb",
    "test/unit/gallery_test.rb",
    "test/unit/photo_test.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rails>, ["= 3.0.3"])
      s.add_runtime_dependency(%q<mysql2>, [">= 0"])
      s.add_runtime_dependency(%q<haml>, ["= 3.0.25"])
      s.add_runtime_dependency(%q<comfortable_mexican_sofa>, ["= 1.0.37"])
      s.add_runtime_dependency(%q<will_paginate>, ["= 2.3.15"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
    else
      s.add_dependency(%q<rails>, ["= 3.0.3"])
      s.add_dependency(%q<mysql2>, [">= 0"])
      s.add_dependency(%q<haml>, ["= 3.0.25"])
      s.add_dependency(%q<comfortable_mexican_sofa>, ["= 1.0.37"])
      s.add_dependency(%q<will_paginate>, ["= 2.3.15"])
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_dependency(%q<rcov>, [">= 0"])
    end
  else
    s.add_dependency(%q<rails>, ["= 3.0.3"])
    s.add_dependency(%q<mysql2>, [">= 0"])
    s.add_dependency(%q<haml>, ["= 3.0.25"])
    s.add_dependency(%q<comfortable_mexican_sofa>, ["= 1.0.37"])
    s.add_dependency(%q<will_paginate>, ["= 2.3.15"])
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
    s.add_dependency(%q<rcov>, [">= 0"])
  end
end

